language: python

python: 3.5
notifications:
  email: false
addons:
  ssh_known_hosts: adicu.com

cache:
  directories:
    - $HOME/.cache/pip
    - webpack/node_modules

before_install:
- export TZ="US/Eastern"
- date

install:
# Install from git commit while waiting for bugfix release
- pip install git+https://github.com/lektor/lektor@d5670a824f2d6436080d7d44632b9388ac355fbc
- gem install html-proofer
script:
- lektor build -f webpack -O $HOME/output
- htmlproofer $HOME/output --file-ignore "/events/201[456].*/,/archive/pages/\d+/"

before_deploy:
- test $TRAVIS_BRANCH == "master"

- openssl aes-256-cbc -K $encrypted_b4089b536350_key -iv $encrypted_b4089b536350_iv -in .ssh/deploy_rsa.enc -out .ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/.ssh/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/.ssh/deploy_rsa

- git config user.name "ADI-Bot"
- git config user.email "infrastructure@adicu.com"
- scripts/travis-commit.sh

deploy:
  provider: script
  script: lektor deploy -O $HOME/output beta
  on:
    branch: master
